# Generated by Django 4.2.7 on 2025-12-10 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInConnectionVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot Upload"),
                            ("profile", "Profile Link"),
                        ],
                        default="screenshot",
                        max_length=20,
                    ),
                ),
                (
                    "profile_url",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profile URL",
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "total_connections",
                    models.IntegerField(
                        help_text="Total number of connections",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "verified_connections_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of verified connections",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reviewer_comments", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_linkedin_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LinkedIn Connection Verification",
                "verbose_name_plural": "LinkedIn Connection Verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerifiedConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Connection's name", max_length=200),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Current company", max_length=200
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, help_text="Job title", max_length=200),
                ),
                (
                    "profile_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn profile URL", max_length=500
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether connection is verified"
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_connections",
                        to="iipc.linkedinconnectionverification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verified Connection",
                "verbose_name_plural": "Verified Connections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screenshot_url",
                    models.URLField(
                        help_text="Google Drive link to screenshot", max_length=500
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="iipc.linkedinconnectionverification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connection Screenshot",
                "verbose_name_plural": "Connection Screenshots",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LinkedInPostVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_url",
                    models.URLField(
                        help_text="LinkedIn post URL",
                        max_length=500,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "post_date",
                    models.DateField(help_text="Date when post was published"),
                ),
                (
                    "character_count",
                    models.IntegerField(
                        help_text="Number of characters in post",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hashtag_count",
                    models.IntegerField(
                        help_text="Number of hashtags used",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "engagement_score",
                    models.IntegerField(
                        help_text="Total engagement (likes + comments + shares)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "likes_count",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "comments_count",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "shares_count",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True, help_text="Positive/Negative/Neutral", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reviewer_comments", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_linkedin_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LinkedIn Post Verification",
                "verbose_name_plural": "LinkedIn Post Verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="iipc_linked_user_id_3dbf5d_idx"
                    ),
                    models.Index(
                        fields=["post_date"], name="iipc_linked_post_da_b7a4cd_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="linkedinconnectionverification",
            index=models.Index(
                fields=["user", "status"], name="iipc_linked_user_id_53f88d_idx"
            ),
        ),
    ]
