# Generated by Django 4.2.7 on 2025-12-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iipc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkedinpostverification",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="linkedinpostverification",
            name="engagement_score",
        ),
        migrations.RemoveField(
            model_name="linkedinpostverification",
            name="likes_count",
        ),
        migrations.RemoveField(
            model_name="linkedinpostverification",
            name="sentiment",
        ),
        migrations.RemoveField(
            model_name="linkedinpostverification",
            name="shares_count",
        ),
    ]
