# Generated by Django 4.2.7 on 2026-02-20 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iipc', '0002_remove_linkedinpostverification_comments_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpostverification',
            name='post_content',
            field=models.TextField(blank=True, help_text='Full text of the post/article pasted by the student for word count and hashtag verification', null=True),
        ),
        migrations.AddField(
            model_name='linkedinpostverification',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('article', 'Article')], default='post', help_text='Type of LinkedIn content (post or article)', max_length=10),
        ),
        migrations.AlterField(
            model_name='linkedinpostverification',
            name='post_url',
            field=models.URLField(help_text='LinkedIn post/article URL', max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
