# Generated by Django 4.2.7 on 2026-02-20 12:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iipc', '0003_add_post_content_and_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IIPCMonthlySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(help_text='Year (e.g. 2026)', validators=[django.core.validators.MinValueValidator(2024)])),
                ('post_1_url', models.URLField(blank=True, max_length=500, null=True)),
                ('post_1_type', models.CharField(choices=[('post', 'Post'), ('article', 'Article')], default='post', max_length=10)),
                ('post_2_url', models.URLField(blank=True, max_length=500, null=True)),
                ('post_2_type', models.CharField(choices=[('post', 'Post'), ('article', 'Article')], default='post', max_length=10)),
                ('post_3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('post_3_type', models.CharField(choices=[('post', 'Post'), ('article', 'Article')], default='post', max_length=10)),
                ('post_4_url', models.URLField(blank=True, max_length=500, null=True)),
                ('post_4_type', models.CharField(choices=[('post', 'Post'), ('article', 'Article')], default='post', max_length=10)),
                ('connection_1_url', models.URLField(blank=True, max_length=500, null=True)),
                ('connection_2_url', models.URLField(blank=True, max_length=500, null=True)),
                ('connection_3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('connection_4_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_iipc_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iipc_monthly_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IIPC Monthly Submission',
                'verbose_name_plural': 'IIPC Monthly Submissions',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
