# Generated by Django 4.2.7 on 2025-12-11 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leetcode_id",
                    models.CharField(
                        blank=True,
                        help_text="LeetCode username",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "github_id",
                    models.CharField(
                        blank=True,
                        help_text="GitHub username",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "linkedin_id",
                    models.CharField(
                        blank=True,
                        help_text="LinkedIn profile URL or ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "indexes": [
                    models.Index(fields=["user"], name="profiles_us_user_id_65af30_idx")
                ],
            },
        ),
    ]
