# Generated by Django 4.2.7 on 2025-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_userprofile_assigned_mentor"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="campus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECH", "SNS College of Technology"),
                    ("ARTS", "SNS College of Arts & Science"),
                ],
                help_text="Campus assignment (Tech or Arts)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="floor",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1st Year"),
                    (2, "2nd Year"),
                    (3, "3rd Year"),
                    (4, "4th Year"),
                ],
                help_text="Floor/Year assignment (1-4 for Tech, 1-3 for Arts)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("MENTOR", "Mentor"),
                    ("FLOOR_WING", "Floor Wing"),
                    ("ADMIN", "Admin"),
                ],
                default="STUDENT",
                help_text="User role in the system",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="profiles_us_role_4fa63b_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["campus", "floor"], name="profiles_us_campus_3bd0a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["assigned_mentor"], name="profiles_us_assigne_a5965e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("campus", "TECH"), ("floor__in", [1, 2, 3, 4])),
                    models.Q(("campus", "ARTS"), ("floor__in", [1, 2, 3])),
                    models.Q(("campus__isnull", True), ("floor__isnull", True)),
                    _connector="OR",
                ),
                name="valid_campus_floor_combination",
            ),
        ),
    ]
