# Generated by Django 4.2.7 on 2025-12-16 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0003_userprofile_campus_userprofile_floor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("important", "Important"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("expired", "Expired"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "campus",
                    models.CharField(
                        choices=[
                            ("TECH", "Technology Campus"),
                            ("ARTS", "Arts & Science Campus"),
                        ],
                        max_length=10,
                    ),
                ),
                ("floor", models.IntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor_wing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_announcements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_floor_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["campus", "floor", "status"],
                        name="profiles_fl_campus_11f649_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="profiles_fl_created_95ef61_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="floorannouncement",
            constraint=models.CheckConstraint(
                check=models.Q(("floor__gte", 1), ("floor__lte", 4)),
                name="valid_floor_announcement_floor_range",
            ),
        ),
    ]
