# Generated by Django 4.2.7 on 2025-12-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_notification"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="floorannouncement",
            name="valid_floor_announcement_floor_range",
        ),
        migrations.RemoveConstraint(
            model_name="userprofile",
            name="valid_campus_floor_combination",
        ),
    ]
