# Generated by Django 4.2.7 on 2026-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_add_scaling_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='floorannouncement',
            name='floor_ann_campus_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='profiles_role_campus_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='profiles_mentor_role_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(blank=True, choices=[('TECH', 'Dr. SNS Rajalakshmi College of Arts and Science'), ('ARTS', 'SNS College of Technology')], help_text='Campus assignment (Tech or Arts)', max_length=10, null=True),
        ),
    ]
