# Generated by Django 4.2.7 on 2026-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_floorannouncement_floor_ann_campus_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='Profile picture URL (Supabase Storage)', max_length=500, null=True),
        ),
    ]
