# Generated by Django 4.2.7 on 2025-12-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_notification_recipient_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="event_date",
            field=models.DateField(
                blank=True, help_text="For deadlines or events", null=True
            ),
        ),
    ]
