# Generated by Django 4.2.7 on 2025-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_announcementread"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="application_deadline",
            field=models.DateField(
                blank=True, help_text="Last date to apply", null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="application_url",
            field=models.URLField(
                blank=True, help_text="Application link", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Company name for job/internship postings",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="job_duration",
            field=models.CharField(
                blank=True,
                help_text="Duration (e.g., '6 months', 'Full-time')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="job_location",
            field=models.CharField(
                blank=True, help_text="Job location", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="job_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on-site", "On-site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                help_text="Work mode",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="job_stipend",
            field=models.CharField(
                blank=True, help_text="Stipend/Salary range", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="required_skills",
            field=models.TextField(
                blank=True, help_text="Comma-separated skills", null=True
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("event", "Event"),
                    ("deadline", "Deadline"),
                    ("important", "Important"),
                    ("reminder", "Reminder"),
                    ("job", "Job Opportunity"),
                    ("internship", "Internship Opportunity"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
