# Generated by Django 4.2.7 on 2025-12-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_announcement_application_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("submission_approved", "Submission Approved"),
                    ("submission_rejected", "Submission Rejected"),
                    ("submission_resubmit", "Resubmission Requested"),
                    ("announcement", "Announcement"),
                    ("message", "New Message"),
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("success", "Success"),
                    ("error", "Error"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
