# Generated by Django 4.2.7 on 2025-12-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clt", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cltfile",
            index=models.Index(
                fields=["submission", "uploaded_at"],
                name="clt_cltfile_submiss_5ee2a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cltsubmission",
            index=models.Index(
                fields=["user", "-created_at"], name="clt_cltsubm_user_id_e89e79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cltsubmission",
            index=models.Index(
                fields=["user", "status"], name="clt_cltsubm_user_id_5531d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cltsubmission",
            index=models.Index(
                fields=["status", "-created_at"], name="clt_cltsubm_status_8630b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cltsubmission",
            index=models.Index(
                fields=["submitted_at"], name="clt_cltsubm_submitt_506c83_idx"
            ),
        ),
    ]
