# Generated by Django 4.2.7 on 2025-12-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clt", "0002_cltfile_clt_cltfile_submiss_5ee2a1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cltsubmission",
            name="drive_link",
            field=models.URLField(
                blank=True,
                help_text="Google Drive link to certificate/evidence",
                max_length=500,
                null=True,
            ),
        ),
    ]
