# Generated by Django 4.2.7 on 2025-12-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clt", "0003_cltsubmission_drive_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="cltsubmission",
            name="duration",
            field=models.IntegerField(
                blank=True, help_text="Total course duration in hours", null=True
            ),
        ),
    ]
