# Generated by Django 4.2.7 on 2025-12-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clt', '0004_cltsubmission_duration'),
        ('clt', '0004_cltsubmission_duration 2'),
    ]

    operations = [
    ]
