# Generated by Django 4.2.7 on 2025-12-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clt', '0004_cltsubmission_duration 3'),
        ('clt', '0005_merge_20251212_1651'),
        ('clt', '0005_merge_20251212_1651 2'),
    ]

    operations = [
    ]
