# Generated by Django 4.2.7 on 2025-12-10 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(help_text="Company name", max_length=255)),
                (
                    "role",
                    models.CharField(
                        help_text="Internship role/position", max_length=255
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("onsite", "On-site"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="Work mode",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="Duration (e.g., '3 months', 'Summer 2025')",
                        max_length=100,
                    ),
                ),
                (
                    "internship_status",
                    models.IntegerField(
                        choices=[
                            (1, "Application"),
                            (2, "Interview"),
                            (3, "Offer"),
                            (4, "Completion"),
                        ],
                        default=1,
                        help_text="Current stage of internship",
                    ),
                ),
                (
                    "completion_certificate_link",
                    models.URLField(
                        blank=True,
                        help_text="Google Drive link to completion certificate",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "lor_link",
                    models.URLField(
                        blank=True,
                        help_text="Google Drive link to Letter of Recommendation",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_comments", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_internships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="cfc_interns_user_id_1cb26f_idx"
                    ),
                    models.Index(
                        fields=["company"], name="cfc_interns_company_be9c61_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HackathonSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hackathon_name",
                    models.CharField(help_text="Name of the hackathon", max_length=255),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="Participation mode",
                        max_length=20,
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(help_text="Date of registration"),
                ),
                (
                    "participation_date",
                    models.DateField(help_text="Date of participation"),
                ),
                (
                    "certificate_link",
                    models.URLField(
                        blank=True,
                        help_text="Google Drive link to certificate",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1, help_text="Current step in submission process"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_comments", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_hackathons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hackathons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="cfc_hackath_user_id_303fb4_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="cfc_hackath_created_10e7c5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GenAIProjectSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_statement",
                    models.TextField(
                        help_text="Description of the problem being solved"
                    ),
                ),
                (
                    "solution_type",
                    models.CharField(
                        choices=[
                            ("web_app", "Web Application"),
                            ("mobile_app", "Mobile Application"),
                            ("api", "API/Backend Service"),
                            ("ml_model", "ML Model"),
                            ("chatbot", "Chatbot"),
                            ("other", "Other"),
                        ],
                        help_text="Type of solution",
                        max_length=50,
                    ),
                ),
                (
                    "innovation_technology",
                    models.TextField(help_text="Technologies and innovations used"),
                ),
                (
                    "innovation_industry",
                    models.CharField(
                        choices=[
                            ("healthcare", "Healthcare"),
                            ("finance", "Finance"),
                            ("education", "Education"),
                            ("ecommerce", "E-commerce"),
                            ("entertainment", "Entertainment"),
                            ("agriculture", "Agriculture"),
                            ("manufacturing", "Manufacturing"),
                            ("other", "Other"),
                        ],
                        help_text="Target industry",
                        max_length=50,
                    ),
                ),
                (
                    "github_repo",
                    models.URLField(help_text="GitHub repository link", max_length=500),
                ),
                (
                    "demo_link",
                    models.URLField(
                        blank=True,
                        help_text="Optional demo/deployment link",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1, help_text="Current step in submission process"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_comments", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_genai_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genai_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="cfc_genaipr_user_id_731003_idx"
                    ),
                    models.Index(
                        fields=["innovation_industry"],
                        name="cfc_genaipr_innovat_4a15bc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BMCVideoSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="YouTube or Drive link to BMC video", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the BMC",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_comments", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_bmc_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bmc_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="cfc_bmcvide_user_id_819898_idx"
                    )
                ],
            },
        ),
    ]
