# Generated by Django 4.2.7 on 2025-12-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genaiprojectsubmission",
            name="innovation_industry",
            field=models.CharField(
                blank=True, help_text="Target industry", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="genaiprojectsubmission",
            name="solution_type",
            field=models.CharField(
                blank=True, help_text="Type of solution", max_length=200
            ),
        ),
    ]
