# Generated by Django 4.2.7 on 2025-12-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfc", "0002_alter_genaiprojectsubmission_innovation_industry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathonsubmission",
            name="github_repo",
            field=models.URLField(
                blank=True,
                help_text="GitHub repository link for hackathon project",
                max_length=500,
                null=True,
            ),
        ),
    ]
