# Generated by Django 4.2.7 on 2025-12-14 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cfc", "0003_hackathonsubmission_github_repo"),
    ]

    operations = [
        migrations.CreateModel(
            name="HackathonRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hackathon_name",
                    models.CharField(help_text="Name of the hackathon", max_length=255),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="Participation mode",
                        max_length=20,
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(help_text="Date when you registered"),
                ),
                (
                    "participation_date",
                    models.DateField(help_text="Scheduled participation date"),
                ),
                (
                    "hackathon_url",
                    models.URLField(
                        blank=True,
                        help_text="Hackathon website or registration link",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes or preparation goals",
                        null=True,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Mark as completed after participation"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, help_text="Track if reminder was shown"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration",
                        to="cfc.hackathonsubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_hackathons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-participation_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_completed"],
                        name="cfc_hackath_user_id_0fdedc_idx",
                    ),
                    models.Index(
                        fields=["participation_date"],
                        name="cfc_hackath_partici_8a7f2b_idx",
                    ),
                ],
            },
        ),
    ]
