# Generated by Django 4.2.7 on 2025-12-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc', '0003_hackathonsubmission_github_repo'),
        ('cfc', '0003_hackathonsubmission_github_repo 2'),
    ]

    operations = [
    ]
