# Generated by Django 4.2.7 on 2025-12-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leetcodeprofile",
            name="monthly_problems_count",
            field=models.IntegerField(
                default=0, help_text="Problems solved this month"
            ),
        ),
        migrations.AddField(
            model_name="leetcodeprofile",
            name="total_active_days",
            field=models.IntegerField(default=0),
        ),
    ]
