# Generated by Django 4.2.7 on 2025-12-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scd", "0002_leetcodeprofile_monthly_problems_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leetcodeprofile",
            name="submission_calendar",
            field=models.JSONField(
                blank=True, default=dict, help_text="Calendar data from LeetCode"
            ),
        ),
    ]
