# Generated by Django 4.2.7 on 2026-02-20 10:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRISubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(help_text='Activity title', max_length=255)),
                ('activity_type', models.CharField(choices=[('environment', 'Environment'), ('community', 'Community Service'), ('education', 'Education'), ('health', 'Health & Welfare'), ('elderly', 'Elderly Care'), ('children', 'Children Welfare'), ('animals', 'Animal Welfare'), ('disaster', 'Disaster Relief'), ('other', 'Other')], default='community', max_length=50)),
                ('activity_date', models.DateField(help_text='Date of activity')),
                ('activity_hours', models.DecimalField(decimal_places=2, help_text='Number of hours spent on activity', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('people_helped', models.PositiveIntegerField(blank=True, help_text='Approximate number of people impacted', null=True)),
                ('description', models.TextField(help_text='Brief description of the activity')),
                ('personal_reflection', models.TextField(help_text='Personal reflection on the experience (max 500 characters)', max_length=500)),
                ('photo_drive_link', models.URLField(help_text='Google Drive link to activity photos', max_length=500)),
                ('organization_name', models.CharField(blank=True, help_text='Name of organization/NGO (if applicable)', max_length=255, null=True)),
                ('certificate_drive_link', models.URLField(blank=True, help_text='Certificate/proof link (if available)', max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sri_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sri_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SRI Submission',
                'verbose_name_plural': 'SRI Submissions',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SRIFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sri_submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('file_type', models.CharField(choices=[('photo', 'Activity Photo'), ('certificate', 'Certificate'), ('proof', 'Proof of Participation'), ('other', 'Other')], default='photo', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sri.srisubmission')),
            ],
            options={
                'verbose_name': 'SRI File',
                'verbose_name_plural': 'SRI Files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='srisubmission',
            index=models.Index(fields=['user', '-activity_date'], name='sri_srisubm_user_id_aef743_idx'),
        ),
        migrations.AddIndex(
            model_name='srisubmission',
            index=models.Index(fields=['user', 'status'], name='sri_srisubm_user_id_e47ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='srisubmission',
            index=models.Index(fields=['status', '-created_at'], name='sri_srisubm_status_7b1e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='srisubmission',
            index=models.Index(fields=['activity_type'], name='sri_srisubm_activit_062d20_idx'),
        ),
        migrations.AddIndex(
            model_name='srisubmission',
            index=models.Index(fields=['submitted_at'], name='sri_srisubm_submitt_665da8_idx'),
        ),
        migrations.AddIndex(
            model_name='srifile',
            index=models.Index(fields=['submission', 'uploaded_at'], name='sri_srifile_submiss_060aaa_idx'),
        ),
    ]
