# Generated by Django 4.2.7 on 2026-02-20 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srisubmission',
            name='activity_date',
            field=models.DateField(auto_now_add=True, help_text='Date of activity'),
        ),
        migrations.AlterField(
            model_name='srisubmission',
            name='activity_hours',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Number of hours spent on activity', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='srisubmission',
            name='personal_reflection',
            field=models.TextField(blank=True, help_text='Personal reflection on the experience', null=True),
        ),
    ]
